### PR TITLE
fix: Remove fs.writeSync as default adapter and add TeamCity setup do…

### LINKED ISSUE #38: Error: EAGAIN: resource temporarily unavailable, write
This error started to appear when updated to node 6.0

It appears randomly when executing a large set of tests. 

This is the full stack of the error:

```
Error: EAGAIN: resource temporarily unavailable, write
    at Error (native)
    at Function.fs.writeSync (fs.js:786:18)
    at /Users/srodriguez/test_project/node_modules/karma/lib/reporters/base.js:51:7
    at Array.forEach (native)
    at write (/Users/srodriguez/test_project/node_modules/karma/lib/reporters/base.js:50:19)
    at flushLogs (/Users/srodriguez/test_project/node_modules/karma-teamcity-reporter/index.js:129:14)
    at getLog (/Users/srodriguez/test_project/node_modules/karma-teamcity-reporter/index.js:117:12)
    at specSkipped (/Users/srodriguez/test_project/node_modules/karma-teamcity-reporter/index.js:84:20)
    at onSpecComplete (/Users/srodriguez/test_project/node_modules/karma/lib/reporters/base.js:76:12)
    at .<anonymous> (/Users/srodriguez/test_project/node_modules/karma/lib/events.js:13:22)
    at emitTwo (events.js:106:13)
    at emit (events.js:191:7)
    at onResult (/Users/srodriguez/test_project/node_modules/karma/lib/browser.js:216:13)
    at Socket.<anonymous> (/Users/srodriguez/test_project/node_modules/karma/lib/events.js:13:22)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at Socket.onevent (/Users/srodriguez/test_project/node_modules/socket.io/lib/socket.js:335:8)
    at Socket.onpacket (/Users/srodriguez/test_project/node_modules/socket.io/lib/socket.js:295:12)
    at Client.ondecoded (/Users/srodriguez/test_project/node_modules/socket.io/lib/client.js:193:14)
    at Decoder.Emitter.emit (/Users/srodriguez/test_project/node_modules/component-emitter/index.js:134:20)
    at Decoder.add (/Users/srodriguez/test_project/node_modules/socket.io-parser/index.js:247:12)
    at Client.ondata (/Users/srodriguez/test_project/node_modules/socket.io/lib/client.js:175:18)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Socket.onPacket (/Users/srodriguez/test_project/node_modules/engine.io/lib/socket.js:101:14)
    at emitOne (events.js:96:13)
    at WebSocket.emit (events.js:188:7)
    at WebSocket.Transport.onPacket (/Users/srodriguez/test_project/node_modules/engine.io/lib/transport.js:104:8)
```

### PR DESCRIPTION
**Pull request by kevcenteno**
…cumentation

Closes #38

### CODE REVIEW

**Comment by kevcenteno** [comment]
I signed it!

**Comment by kevcenteno** [comment]
Unrelated build failure: Failure due to npm no longer supporting node v0.10.  Maybe the CI build should remove this test.

**Comment by kevcenteno** [comment]
Might also fix #25

**Comment by kevcenteno** [comment]
@dignifiedquire Any thoughts on this?

**Comment by dizel3d** [comment]
@kevcenteno, it works, thank you!

Generally, the PR just reverted the fix https://github.com/karma-runner/karma-teamcity-reporter/commit/d8d9e70630031de66036d81b396561fb6de20f70, which isn't actual anymore. (https://github.com/karma-runner/karma-teamcity-reporter/issues/32#issuecomment-197908787 explains why.) So look forward to merge.

**Comment by dizel3d** [comment]
@kevcenteno, rebase your PR to actual `master`, please, to fix `travis-ci` build.

**Comment by kevcenteno** [comment]
Rebased

**Comment by kevcenteno** [comment]
@dignifiedquire @dizel3d Tests are passing and ready for merge

**Comment by dignifiedquire** [comment]
Thank you :octocat:

**Pull request merged**
