### PR TITLE
Replaced the default adapter with fs.writeSync to make sure all tests are reported

### PR DESCRIPTION
**Pull request by nievebc**
...before process ends.
This is @kdrvn work which I have simply copy pasted into a pull request for issue #5 - if this work is not accepted, please let me know why, so that I could look into fixing it properly.

### CODE REVIEW

**Comment by gzurbach** [comment]
+1!

**Comment by nievebc** [comment]
By the way- the Travis failure message shows the error is to do with some dependencies incompatibilities rather than any code issue. I will try to look into it asap unless someone else will beat me to it.

**Comment by Chinow** [comment]
I would love to see this bug fixed to have consistent reports.

**Comment by AlexCuse** [comment]
:+1: 

We have been running this for quite a while as well.  Due to some eccentricities with our system, git installs won't work so we need to pack it ourselves and check in a tarball to install from before running npm install for our test dependencies.  This feels quite fragile, would love to have a working version of the reporter available through NPM.

**Comment by liam-swinney** [comment]
Hi guys,  any update on this?  Would love this to work then we can start using this plugin

**Comment by Dignifiedquire** [comment]
Thanks and sorry for the long wait

**Pull request merged**
