### PR TITLE
avoid large strings in memory

### LINKED ISSUE #33: out of memory error writing log in windows
Hi
When running a big test suite with descriptive tests in karma on a windows machine I get an out of memory error when the reporter writes the log.

It looks like the error originates from [the writing of log.join(' ' ) all at once](https://github.com/karma-runner/karma-teamcity-reporter/blob/master/index.js#L125) which overruns the OS write buffer or something. 
A local fix where the log is written one item at a time solves the issue. I'd be happy to offer a PR but I understand you're using the atomic filesystem write as a locking mechanism, so I'd like to know if this approach is something I can expect to be merged into the master branch.

```
##teamcity[blockOpened name='Chrome 45.0.2454 (Windows 7 0.0.0)']
Missing error handler on `socket`.
Error: ENOMEM, not enough memory
    at Error (native)
    at Function.fs.writeSync (fs.js:619:18)
    at C:\projects\my-project\node_modules\karma\lib\reporters\base.js:51:7
    at Array.forEach (native)
    at write (C:\projects\my-project\node_modules\karma\lib\reporters\base.js:50:19)
    at C:\projects\my-project\node_modules\karma-teamcity-reporter\index.js:98:12
    at Array.forEach (native)
    at onRunComplete (C:\projects\my-project\node_modules\karma-teamcity-reporter\index.js:90:38)
    at null.<anonymous> (C:\projects\my-project\node_modules\karma\lib\events.js:13:22)
    at emit (events.js:129:20)
    at emitRunCompleteIfAllBrowsersDone (C:\projects\my-project\node_modules\karma\lib\server.js:252:12)
    at null.<anonymous> (C:\projects\my-project\node_modules\karma\lib\server.js:274:9)
    at emit (events.js:129:20)
    at onComplete (C:\projects\my-project\node_modules\karma\lib\browser.js:142:13)
    at Socket.<anonymous> (C:\projects\my-project\node_modules\karma\lib\events.js:13:22)
    at Socket.emit (events.js:129:20)
04 11 2015 12:05:26.917:WARN [Chrome 45.0.2454 (Windows 7 0.0.0)]: Disconnected (1 times), because no message in 10000 ms.
##teamcity[blockOpened name='Chrome 45.0.2454 (Windows 7 0.0.0)']
04 11 2015 12:05:26.922:ERROR [karma]: { [Error: ENOMEM, not enough memory] errno: -4057, code: 'ENOMEM', syscall: 'write' }
Error: ENOMEM, not enough memory
    at Error (native)
    at Function.fs.writeSync (fs.js:619:18)
    at C:\projects\my-project\node_modules\karma\lib\reporters\base.js:51:7
    at Array.forEach (native)
    at write (C:\projects\my-project\node_modules\karma\lib\reporters\base.js:50:19)
    at C:\projects\my-project\node_modules\karma-teamcity-reporter\index.js:98:12
    at Array.forEach (native)
    at onRunComplete (C:\projects\typorama\node_modules\karma-teamcity-reporter\index.js:90:38)
    at null.<anonymous> (C:\projects\my-project\node_modules\karma\lib\events.js:13:22)
    at emit (events.js:129:20)
    at emitRunCompleteIfAllBrowsersDone (C:\projects\my-project\node_modules\karma\lib\server.js:252:12)
    at null.<anonymous> (C:\projects\my-project\node_modules\karma\lib\server.js:274:9)
    at emit (events.js:129:20)
    at null._onTimeout (C:\projects\my-project\node_modules\karma\lib\browser.js:50:15)
    at Timer.listOnTimeout (timers.js:110:15)

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "c:\\Program Files\\nodejs\\\\node.exe" "c:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "test:browser"
npm ERR! node v0.12.4
npm ERR! npm  v2.10.1
npm ERR! code ELIFECYCLE
npm ERR! my-project@0.0.112 test:browser: `karma start --single-run --log-level warn`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the my-project@0.0.112 test:browser script 'karma start --single-run --log-level warn'.
npm ERR! This is most likely a problem with the my-project package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     karma start --single-run --log-level warn
npm ERR! You can get their info via:
npm ERR!     npm owner ls typorama
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\projects\typorama\npm-debug.log
$my-project@0.0.112 test:browser: `karma start --single-run --log-level warn`
```

### PR DESCRIPTION
**Pull request by amir-arad**
fixes #33

### CODE REVIEW

**Comment by amir-arad** [comment]
I signed it!

**Comment by amir-arad** [comment]
That lint rule rejects pre-existing code

**Comment by amir-arad** [comment]
hey @dignifiedquire how about that weather? :)

**Comment by dignifiedquire** [comment]
Thanks, I've fixed the lint issues on master, can you please rebase onto master, squash your commits into one and make sure the commit message follows our [convention](http://karma-runner.github.io/0.13/dev/git-commit-msg.html).

**Comment by amir-arad** [comment]
Thanks, I'll get to it :)

**Comment by dignifiedquire** [comment]
Merged in 5c8b8ad3ad66d6e1c55601d9e3b87653fbc0a46c

**Pull request closed without merging**
